
# This doesn't include kewords for actions like Manifest Dread
KEYWORDS = \
["Eerie", "Battalion", "Bloodrush", "Channel", "Chroma", "Cohort", "Constellation",
"Converge", "Delirium", "Domain", "Fateful hour", "Ferocious", "Formidable", "Grandeur",
"Hellbent", "Heroic", "Imprint", "Inspired", "Join forces", "Kinship", "Landfall",
"Lieutenant", "Metalcraft", "Morbid", "Parley", "Radiance", "Raid", "Rally", "Spell mastery",
"Strive", "Sweep", "Tempting offer", "Threshold", "Will of the council", "Adamant",
"Addendum", "Council's dilemma", "Eminence", "Enrage", "Hero's Reward", "Kinfall",
"Landship", "Legacy", "Revolt", "Underdog", "Undergrowth", "Descend", "Fathomless descent",
"Magecraft", "Teamwork", "Pack tactics", "Coven", "Alliance", "Corrupted", "Secret council",
"Celebration", "Paradox", "Will of the Planeswalkers", "Survival", "Valiant",
"Start your engines!", "Living weapon", "Jump-start", "Commander ninjutsu",
"Legendary landwalk", "Nonbasic landwalk", "Megamorph", "Haunt", "Forecast", "Graft",
"Fortify", "Frenzy", "Gravestorm", "Hideaway", "Level Up", "Infect", "Reach", "Rampage",
"Phasing", "Multikicker", "Morph", "Provoke", "Modular", "Ninjutsu", "Replicate", "Recover",
"Poisonous", "Prowl", "Reinforce", "Persist", "Retrace", "Rebound", "Miracle", "Overload",
"Outlast", "Prowess", "Renown", "Myriad", "Shroud", "Trample", "Vigilance", "Storm",
"Soulshift", "Splice", "Transmute", "Ripple", "Suspend", "Vanishing", "Transfigure",
"Wither", "Undying", "Soulbond", "Unleash", "Ascend", "Assist", "Afterlife", "Companion",
"Fabricate", "Embalm", "Escape", "Fuse", "Menace", "Ingest", "Melee", "Improvise", "Mentor",
"Partner", "Mutate", "Tribute", "Surge", "Skulk", "Undaunted", "Riot", "Spectacle",
"Forestwalk", "Islandwalk", "Mountainwalk", "Double strike", "Cumulative upkeep",
"First strike", "Scavenge", "Encore", "Deathtouch", "Defender", "Amplify", "Affinity",
"Bushido", "Convoke", "Bloodthirst", "Absorb", "Aura Swap", "Changeling", "Conspire",
"Cascade", "Annihilator", "Battle Cry", "Cipher", "Bestow", "Dash", "Awaken", "Crew",
"Aftermath", "Afflict", "Flanking", "Foretell", "Fading", "Fear", "Eternalize", "Entwine",
"Epic", "Dredge", "Delve", "Evoke", "Exalted", "Evolve", "Extort", "Dethrone", "Exploit",
"Devoid", "Emerge", "Escalate", "Flying", "Haste", "Hexproof", "Indestructible",
"Intimidate", "Lifelink", "Horsemanship", "Kicker", "Madness", "Swampwalk", "Desertwalk",
"Craft", "Plainswalk", "Split second", "Augment", "Double agenda", "Reconfigure", "Ward",
"Partner with", "Daybound", "Nightbound", "Decayed", "Disturb", "Squad", "Enlist",
"Read Ahead", "Ravenous", "Blitz", "Offering", "Living metal", "Backup", "Banding",
"Hidden agenda", "For Mirrodin!", "Friends forever", "Casualty", "Protection",
"Compleated", "Devour", "Enchant", "Flash", "Boast", "Demonstrate", "Sunburst",
"Flashback", "Cycling", "Equip", "Buyback", "Hexproof from", "More Than Meets the Eye",
"Cleave", "Champion", "Specialize", "Training", "Prototype", "Toxic", "Unearth",
"Intensity", "Plainscycling", "Swampcycling", "Typecycling", "Wizardcycling",
"Mountaincycling", "Basic landcycling", "Islandcycling", "Forestcycling", "Slivercycling",
"Landcycling", "Bargain", "Choose a background", "Echo", "Disguise", "Doctor's companion",
"Landwalk", "Umbra armor", "Freerunning", "Spree", "Saddle", "Shadow", "Offspring",
"Impending", "Gift", "Exhaust"]

planeswalker_genders = {
    "Ajani": "masc",
    "Aminatou": "fem",
    "Angrath": "masc",
    "Arlinn": "fem",
    "Ashiok": "unknown",
    "Bahamut": "masc",
    "Basri": "masc",
    "Bolas": "masc",
    "Calix": "masc",
    "Chandra": "fem",
    "Comet": "masc",
    "Dack": "masc",
    "Dakkon": "masc",
    "Daretti": "masc",
    "Davriel": "masc",
    "Dihada": "fem",
    "Domri": "masc",
    "Dovin": "masc",
    "Ellywick": "fem",
    "Elminster": "masc",
    "Elspeth": "fem",
    "Estrid": "fem",
    "Freyalise": "fem",
    "Garruk": "masc",
    "Gideon": "masc",
    "Grist": "fem",
    "Guff": "masc",
    "Huatli": "fem",
    "Jace": "masc",
    "Jared": "masc",
    "Jaya": "fem",
    "Jeska": "fem",
    "Kaito": "masc",
    "Karn": "masc",
    "Kasmina": "fem",
    "Kaya": "fem",
    "Kiora": "fem",
    "Koth": "masc",
    "Liliana": "fem",
    "Lolth": "fem",
    "Lukka": "masc",
    "Minsc": "masc",
    "Mordenkainen": "masc",
    "Nahiri": "fem",
    "Narset": "fem",
    "Niko": "nonbinary",
    "Nissa": "fem",
    "Nixilis": "masc",
    "Oko": "masc",
    "Quintorius": "masc",
    "Ral": "masc",
    "Rowan": "fem",
    "Saheeli": "fem",
    "Samut": "fem",
    "Sarkhan": "masc",
    "Serra": "fem",
    "Sivitri": "fem",
    "Sorin": "masc",
    "Szat": "masc",
    "Tamiyo": "fem",
    "Tasha": "fem",
    "Teferi": "masc",
    "Teyo": "masc",
    "Tezzeret": "masc",
    "Tibalt": "masc",
    "Tyvar": "masc",
    "Ugin": "masc",
    "Urza": "masc",
    "Venser": "masc",
    "Vivien": "fem",
    "Vraska": "fem",
    "Vronos": "masc",
    "Will": "masc",
    "Windgrace": "masc",
    "Wrenn": "fem",
    "Xenagos": "masc",
    "Yanggu": "masc",
    "Yanling": "fem",
    "Zariel": "fem"
}

fade_mappings = {
    "WU": ("Left", "Right", "W", "U"),
    "WB": ("Left", "Right", "W", "B"),
    "RW": ("Right", "Left", "W", "R"),
    "GW": ("Right", "Left", "W", "G"),
    "UB": ("Left", "Right", "U", "B"),
    "UR": ("Left", "Right", "U", "R"),
    "GU": ("Right", "Left", "U", "G"),
    "BR": ("Left", "Right", "B", "R"),
    "BG": ("Left", "Right", "B", "G"),
    "RG": ("Left", "Right", "R", "G")
}

# This includes color orders which don't normally exist on cards
# Used for adventure card textboxes
extended_fade_mappings = {
    "WU": ("Left", "Right", "W", "U"),
    "WB": ("Left", "Right", "W", "B"),
    "RW": ("Right", "Left", "W", "R"),
    "GW": ("Right", "Left", "W", "G"),
    "UB": ("Left", "Right", "U", "B"),
    "UR": ("Left", "Right", "U", "R"),
    "GU": ("Right", "Left", "U", "G"),
    "BR": ("Left", "Right", "B", "R"),
    "BG": ("Left", "Right", "B", "G"),
    "RG": ("Left", "Right", "R", "G"),
    "UW": ("Right", "Left", "W", "U"),
    "BW": ("Right", "Left", "W", "B"),
    "WR": ("Left", "Right", "W", "R"),
    "WG": ("Left", "Right", "W", "G"),
    "BU": ("Right", "Left", "U", "B"),
    "RU": ("Right", "Left", "U", "R"),
    "UG": ("Left", "Right", "U", "G"),
    "RB": ("Right", "Left", "B", "R"),
    "GB": ("Right", "Left", "B", "G"),
    "GR": ("Right", "Left", "R", "G")
}

ordered_textbox_textures = [
    "Legends",
    "Land",
    "WL",
    "UL",
    "BL",
    "RL",
    "GL",
    "WL Dual",
    "UL Dual",
    "BL Dual",
    "RL Dual",
    "GL Dual",
    "W",
    "U",
    "B",
    "R",
    "G",
    "Gold",
    "Artifact",
    "Colorless"
]

ordered_frame_textures = [
    "W",
    "U",
    "B",
    "R",
    "G",
    "Gold",
    "Colorless",
    "Artifact",
    "Land",
    "Legends Land"
]

color_word_map = {
    "W": "white",
    "U": "blue",
    "B": "black",
    "R": "red",
    "G": "green",
    "C": "colorless"
}

# Color maps are for pinline colors

land_color_map = {
    'W': [217, 206, 200],
    'U': [12, 97, 122],
    'B': [76, 72, 71],
    'R': [199, 78, 49],  # Changed from CMM to 7ED for more saturation
    'G': [99, 142, 85],
    'Land': [244, 172, 38],
}

dual_land_color_map = {
    'W': [224, 217, 215],
    'U': [0, 119, 158],
    'B': [82, 81, 74],
    'R': [237, 97, 59],
    'G': [146, 192, 48],
    'Land': [244, 172, 38],
}

nonland_color_map = {
    'W': [217, 206, 200],
    'U': [12, 97, 122],
    'B': [76, 72, 71],
    'R': [198, 118, 89],
    'G': [99, 142, 85],
    'Gold': [184, 165, 110],
    'Artifact': [139, 124, 108],
    'Colorless': [198, 198, 198]
}